import { test, expect } from '@playwright/test';
import { createHash } from 'node:crypto';
const bytes = Buffer.from('Geverifieerde toetsinhoud.');
const hash = createHash('sha256').update(bytes).digest('hex');
const asset = { id: 'dance-lyrics', title: 'Toets woorde', kind: 'lyrics', path: `content/${hash}`, sha256: hash, bytes: bytes.length, mime: 'text/plain', version: '1.0.0' };
function catalog(withAsset = true) { return { schemaVersion: 1, version: '1.0.0', entries: [{ id: 'aanstap-rooies', title: 'Aanstap Rooies', number: 1, category: 'dance', description: 'Leer die passies.', assets: withAsset ? [asset] : [] }] }; }
test('verified download survives offline launch and failed replacement', async ({ page }) => {
  let content = bytes;
  let current = catalog();
  await page.route('https://niclan1.github.io/automatic-waffle/**', route => {
    const url = route.request().url();
    if (url.endsWith('catalog.json')) return route.fulfill({ json: current });
    if (url.endsWith('app.json')) return route.fulfill({ json: { version: '0.1.0', url: 'https://github.com/Niclan1/automatic-waffle/releases/latest' } });
    return route.fulfill({ body: content });
  });
  await page.goto('/');
  await page.getByRole('button', { name: 'Ontdek die liedjies' }).click();
  await page.getByRole('button', { name: /Aanstap Rooies/ }).click();
  await page.getByRole('button', { name: 'Laai af', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Maak oop' })).toBeVisible();
  await page.getByRole('button', { name: 'Maak oop' }).click();
  await expect(page.locator('dialog')).toContainText(bytes.toString());
  await page.getByRole('button', { name: 'Sluit lêer' }).click();
  const changed = Buffer.from('Nuwe toetsinhoud!');
  current.entries[0].assets[0] = { ...asset, sha256: createHash('sha256').update(changed).digest('hex'), bytes: changed.length, path: `content/${createHash('sha256').update(changed).digest('hex')}`, version: '1.1.0' };
  content = Buffer.from('Wrong bytes!');
  await page.getByRole('button', { name: 'Kyk vir opdaterings' }).click();
  await expect(page.getByRole('button', { name: 'Werk by' })).toBeVisible();
  await page.getByRole('button', { name: 'Werk by' }).click();
  await expect(page.getByRole('status')).toContainText('integriteitskontrole');
  await page.getByRole('button', { name: 'Maak oop' }).click();
  await expect(page.locator('dialog')).toContainText(bytes.toString());
  await page.getByRole('button', { name: 'Sluit lêer' }).click();
  await page.unroute('https://niclan1.github.io/automatic-waffle/**');
  await page.route('https://niclan1.github.io/automatic-waffle/**', route => route.abort());
  await page.reload();
  await expect(page.getByText('Vanlyn · Jou gestoorde lêers is steeds beskikbaar.')).toBeVisible();
  await page.getByRole('button', { name: /My aflaaie/ }).first().click();
  await page.getByRole('button', { name: 'Maak oop' }).click();
  await expect(page.locator('dialog')).toContainText(bytes.toString());
  await page.getByRole('button', { name: 'Sluit lêer' }).click();
  await page.getByRole('button', { name: 'Verwyder Toets woorde' }).click();
  await expect(page.getByText('Maak plek vir jou gunstelinge')).toBeVisible();
});
test('mobile navigation, search, pending content and app update link', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.route('https://niclan1.github.io/automatic-waffle/**', route => route.fulfill({ json: route.request().url().endsWith('catalog.json') ? catalog(false) : { version: '0.2.0', url: 'https://github.com/Niclan1/automatic-waffle/releases/tag/v0.2.0' } }));
  await page.goto('/');
  await page.getByRole('button', { name: 'Ontdek die liedjies' }).click();
  await expect(page.getByText('Volkspele 0.2.0 is beskikbaar.')).toBeVisible();
  await page.getByRole('textbox', { name: 'Soek in biblioteek' }).fill('no-match');
  await expect(page.getByText('Geen resultate nie')).toBeVisible();
  await page.getByRole('button', { name: 'Maak soektog skoon' }).click();
  await page.getByRole('button', { name: /Aanstap Rooies/ }).click();
  await expect(page.getByRole('heading', { name: 'Inhoud word voorberei' })).toBeVisible();
  await page.getByRole('button', { name: 'Maak kieslys oop' }).click();
  await page.getByRole('button', { name: /My aflaaie/ }).first().click();
  await expect(page.getByRole('heading', { name: 'My aflaaie' })).toBeVisible();
  await expect(page.locator('body')).toHaveJSProperty('scrollWidth', 390);
});
